version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: anantbuy-frontend
    ports:
      - "4000:3000"
    depends_on:
      - backend
    networks:
      - default

  backend:
    build: ./backend
    container_name: anantbuy-api
    ports:
      - "9000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      default:
      anant-monitoring:
        aliases:
          - anantbuy-api

  postgres:
    image: postgres:16
    container_name: anantbuy-postgres
    environment:
      POSTGRES_USER: anantbuy
      POSTGRES_PASSWORD: AnantBuy123
      POSTGRES_DB: anantbuy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:

networks:
  anant-monitoring:
    name: anant-monitoring  