version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: anantbuy-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/vibhorkdew/anantbuy-backend:latest
    container_name: anantbuy-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/code/logs
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  frontend:
    image: ghcr.io/vibhorkdew/anantbuy-frontend:latest
    container_name: anantbuy-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4000:80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: