name: AnantBuy Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/AnantBuy

            docker compose version

            docker login ghcr.io \
              -u ${{ github.repository_owner }} \
              -p ${{ secrets.GHCR_TOKEN }}

            docker compose pull

            docker compose up -d --remove-orphans

            docker image prune -f

            docker ps